# Generated by Django 6.0 on 2025-12-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del taller')),
            ],
            options={
                'verbose_name': 'Asignar Taller',
                'verbose_name_plural': 'Asignaciones de Talleres',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mesa de Trabajo',
                'verbose_name_plural': 'Mesas de Trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_by_reference', models.PositiveIntegerField(verbose_name='Cantidad por referencia')),
                ('quantity_by_color', models.PositiveIntegerField(verbose_name='Cantidad por color')),
                ('quantity_by_size', models.PositiveIntegerField(verbose_name='Cantidad por talla')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuts', to='cutting.color')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuts', to='cutting.material')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='cutting.reference')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuts', to='cutting.size')),
            ],
            options={
                'verbose_name': 'Corte',
                'verbose_name_plural': 'Cortes',
            },
        ),
        migrations.CreateModel(
            name='CuttingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_by_color', models.PositiveIntegerField(verbose_name='Assigned Quantity by Color')),
                ('quantity_by_size', models.PositiveIntegerField(verbose_name='Assigned Quantity by Size')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cutting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cutting.cutting', verbose_name='Cutting')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cutting.workshop', verbose_name='Taller asignado')),
            ],
            options={
                'verbose_name': 'Cutting Assignment',
                'verbose_name_plural': 'Cutting Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
