# Generated by Django 6.0 on 2025-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Asignar Taller',
                'verbose_name_plural': 'Asignaciones de Talleres',
                'ordering': ['id'],
            },
        ),
    ]
