# Generated by Django 6.0 on 2025-12-13 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0002_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='estimated_delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha estimada de entrega'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='quantity_assigned',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad asignada'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_assignments', to='cutting.reference', verbose_name='Tipo de prenda asignada'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('in_process', 'En proceso'), ('ready', 'Listo'), ('returned', 'Devuelto'), ('rejected', 'Rechazado')], default='in_process', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del taller'),
        ),
    ]
