# Generated by Django 6.0 on 2025-12-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0003_workshop_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='estimated_delivery_date',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='quantity_assigned',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='status',
        ),
    ]
