# Generated by Django 6.0 on 2025-12-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0004_remove_workshop_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField(verbose_name='Cantidad asignada')),
                ('estimated_delivery_date', models.DateField(verbose_name='Fecha estimada de entrega')),
                ('status', models.CharField(choices=[('in_process', 'En proceso'), ('ready', 'Listo'), ('returned', 'Devuelto'), ('rejected', 'Rechazado')], default='in_process', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cutting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cutting.cutting', verbose_name='Lote')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cutting.workshop', verbose_name='Taller asignado')),
            ],
            options={
                'verbose_name': 'Asignación de Corte',
                'verbose_name_plural': 'Asignaciones de Cortes',
                'ordering': ['id'],
            },
        ),
    ]
