# Generated by Django 6.0 on 2025-12-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0005_cuttingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Información adicional'),
        ),
    ]
