# Generated by Django 6.0 on 2025-12-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0006_cutting_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='cut_date',
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='work_table',
        ),
    ]
